% create study

% ASR
%L
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ASR_L', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ASR\ERSP-Study\sets\001 malgorzata_ASR_after_BadChanRem_5_L.set' 'subject' 'Malgorzata001' 'condition' 'L' 'group' 'ASR' }, ...
	{ 'index' 2 'load' 'data_in_groups\ASR\ERSP-Study\sets\002 paulina_ASR_after_BadChanRem_5_L.set' 'subject' 'Paulina002' 'condition' 'L' 'group' 'ASR' }, ...
	{ 'index' 3 'load' 'data_in_groups\ASR\ERSP-Study\sets\004 michal_ASR_after_BadChanRem_5_L.set' 'subject' 'Michal004' 'condition' 'L' 'group' 'ASR' }, ...
	{ 'index' 4 'load' 'data_in_groups\ASR\ERSP-Study\sets\bernadetta_ASR_after_BadChanRem_5_L.set' 'subject' 'Bernadetta' 'condition' 'L' 'group' 'ASR' }, ...
	{ 'index' 5 'load' 'data_in_groups\ASR\ERSP-Study\sets\darekz3_ASR_after_BadChanRem_5_L.set' 'subject' 'DarekZ3' 'condition' 'L' 'group' 'ASR' }, ...
	{ 'index' 6 'load' 'data_in_groups\ASR\ERSP-Study\sets\gosiapw_ASR_after_BadChanRem_5_L.set' 'subject' 'GosiaPW' 'condition' 'L' 'group' 'ASR' }, ...	
        { 'index' 7 'load' 'data_in_groups\ASR\ERSP-Study\sets\kingapl_ASR_after_BadChanRem_5_L.set' 'subject' 'KingaPl' 'condition' 'L' 'group' 'ASR' }, ...	
        { 'index' 8 'load' 'data_in_groups\ASR\ERSP-Study\sets\martyna_ASR_after_BadChanRem_5_L.set' 'subject' 'Martyna' 'condition' 'L' 'group' 'ASR' }, ...	
        { 'index' 9 'load' 'data_in_groups\ASR\ERSP-Study\sets\monika_ASR_after_BadChanRem_5_L.set' 'subject' 'Monika' 'condition' 'L' 'group' 'ASR' }, ...	
        { 'index' 10 'load' 'data_in_groups\ASR\ERSP-Study\sets\natalia_correct_locs_ASR_after_BadChanRem_5_L.set' 'subject' 'Natalia' 'condition' 'L' 'group' 'ASR' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ASR_L.study', 'filepath', 'data_in_groups\ASR\ERSP-Study\');


% ASR
%R
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ASR_R', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ASR\ERSP-Study\sets\001 malgorzata_ASR_after_BadChanRem_5_R.set' 'subject' 'Malgorzata001' 'condition' 'R' 'group' 'ASR' }, ...
	{ 'index' 2 'load' 'data_in_groups\ASR\ERSP-Study\sets\002 paulina_ASR_after_BadChanRem_5_R.set' 'subject' 'Paulina002' 'condition' 'R' 'group' 'ASR' }, ...
	{ 'index' 3 'load' 'data_in_groups\ASR\ERSP-Study\sets\004 michal_ASR_after_BadChanRem_5_R.set' 'subject' 'Michal004' 'condition' 'R' 'group' 'ASR' }, ...
	{ 'index' 4 'load' 'data_in_groups\ASR\ERSP-Study\sets\bernadetta_ASR_after_BadChanRem_5_R.set' 'subject' 'Bernadetta' 'condition' 'R' 'group' 'ASR' }, ...
	{ 'index' 5 'load' 'data_in_groups\ASR\ERSP-Study\sets\darekz3_ASR_after_BadChanRem_5_R.set' 'subject' 'DarekZ3' 'condition' 'R' 'group' 'ASR' }, ...
	{ 'index' 6 'load' 'data_in_groups\ASR\ERSP-Study\sets\gosiapw_ASR_after_BadChanRem_5_R.set' 'subject' 'GosiaPW' 'condition' 'R' 'group' 'ASR' }, ...	
        { 'index' 7 'load' 'data_in_groups\ASR\ERSP-Study\sets\kingapl_ASR_after_BadChanRem_5_R.set' 'subject' 'KingaPl' 'condition' 'R' 'group' 'ASR' }, ...	
        { 'index' 8 'load' 'data_in_groups\ASR\ERSP-Study\sets\martyna_ASR_after_BadChanRem_5_R.set' 'subject' 'Martyna' 'condition' 'R' 'group' 'ASR' }, ...	
        { 'index' 9 'load' 'data_in_groups\ASR\ERSP-Study\sets\monika_ASR_after_BadChanRem_5_R.set' 'subject' 'Monika' 'condition' 'R' 'group' 'ASR' }, ...	
        { 'index' 10 'load' 'data_in_groups\ASR\ERSP-Study\sets\natalia_correct_locs_ASR_after_BadChanRem_5_R.set' 'subject' 'Natalia' 'condition' 'R' 'group' 'ASR' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ASR_R.study', 'filepath', 'data_in_groups\ASR\ERSP-Study\');


% ASR
%Rest
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ASR_Rest', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ASR\ERSP-Study\sets\001 malgorzata_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Malgorzata001' 'condition' 'Rest' 'group' 'ASR' }, ...
	{ 'index' 2 'load' 'data_in_groups\ASR\ERSP-Study\sets\002 paulina_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Paulina002' 'condition' 'Rest' 'group' 'ASR' }, ...
	{ 'index' 3 'load' 'data_in_groups\ASR\ERSP-Study\sets\004 michal_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Michal004' 'condition' 'Rest' 'group' 'ASR' }, ...
	{ 'index' 4 'load' 'data_in_groups\ASR\ERSP-Study\sets\bernadetta_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Bernadetta' 'condition' 'Rest' 'group' 'ASR' }, ...
	{ 'index' 5 'load' 'data_in_groups\ASR\ERSP-Study\sets\darekz3_ASR_after_BadChanRem_5_Rest.set' 'subject' 'DarekZ3' 'condition' 'Rest' 'group' 'ASR' }, ...
	{ 'index' 6 'load' 'data_in_groups\ASR\ERSP-Study\sets\gosiapw_ASR_after_BadChanRem_5_Rest.set' 'subject' 'GosiaPW' 'condition' 'Rest' 'group' 'ASR' }, ...	
        { 'index' 7 'load' 'data_in_groups\ASR\ERSP-Study\sets\kingapl_ASR_after_BadChanRem_5_Rest.set' 'subject' 'KingaPl' 'condition' 'Rest' 'group' 'ASR' }, ...	
        { 'index' 8 'load' 'data_in_groups\ASR\ERSP-Study\sets\martyna_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Martyna' 'condition' 'Rest' 'group' 'ASR' }, ...	
        { 'index' 9 'load' 'data_in_groups\ASR\ERSP-Study\sets\monika_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Monika' 'condition' 'Rest' 'group' 'ASR' }, ...	
        { 'index' 10 'load' 'data_in_groups\ASR\ERSP-Study\sets\natalia_correct_locs_ASR_after_BadChanRem_5_Rest.set' 'subject' 'Natalia' 'condition' 'Rest' 'group' 'ASR' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ASR_Rest.study', 'filepath', 'data_in_groups\ASR\ERSP-Study\');


% ICA
%L
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ICA_L', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ICA\ERSP-Study\sets\001 malgorzata_ICA_after_BadChanRem_5_L.set' 'subject' 'Malgorzata001' 'condition' 'L' 'group' 'ICA' }, ...
	{ 'index' 2 'load' 'data_in_groups\ICA\ERSP-Study\sets\002 paulina_ICA_after_BadChanRem_5_L.set' 'subject' 'Paulina002' 'condition' 'L' 'group' 'ICA' }, ...
	{ 'index' 3 'load' 'data_in_groups\ICA\ERSP-Study\sets\004 michal_ICA_after_BadChanRem_5_L.set' 'subject' 'Michal004' 'condition' 'L' 'group' 'ICA' }, ...
	{ 'index' 4 'load' 'data_in_groups\ICA\ERSP-Study\sets\bernadetta_ICA_after_BadChanRem_5_L.set' 'subject' 'Bernadetta' 'condition' 'L' 'group' 'ICA' }, ...
	{ 'index' 5 'load' 'data_in_groups\ICA\ERSP-Study\sets\darekz3_ICA_after_BadChanRem_5_L.set' 'subject' 'DarekZ3' 'condition' 'L' 'group' 'ICA' }, ...
	{ 'index' 6 'load' 'data_in_groups\ICA\ERSP-Study\sets\gosiapw_ICA_after_BadChanRem_5_L.set' 'subject' 'GosiaPW' 'condition' 'L' 'group' 'ICA' }, ...	
        { 'index' 7 'load' 'data_in_groups\ICA\ERSP-Study\sets\kingapl_ICA_after_BadChanRem_5_L.set' 'subject' 'KingaPl' 'condition' 'L' 'group' 'ICA' }, ...	
        { 'index' 8 'load' 'data_in_groups\ICA\ERSP-Study\sets\martyna_ICA_after_BadChanRem_5_L.set' 'subject' 'Martyna' 'condition' 'L' 'group' 'ICA' }, ...	
        { 'index' 9 'load' 'data_in_groups\ICA\ERSP-Study\sets\monika_ICA_after_BadChanRem_5_L.set' 'subject' 'Monika' 'condition' 'L' 'group' 'ICA' }, ...	
        { 'index' 10 'load' 'data_in_groups\ICA\ERSP-Study\sets\natalia_correct_locs_ICA_after_BadChanRem_5_L.set' 'subject' 'Natalia' 'condition' 'L' 'group' 'ICA' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ICA_L.study', 'filepath', 'data_in_groups\ICA\ERSP-Study\');


% ICA
%R
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ICA_R', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ICA\ERSP-Study\sets\001 malgorzata_ICA_after_BadChanRem_5_R.set' 'subject' 'Malgorzata001' 'condition' 'R' 'group' 'ICA' }, ...
	{ 'index' 2 'load' 'data_in_groups\ICA\ERSP-Study\sets\002 paulina_ICA_after_BadChanRem_5_R.set' 'subject' 'Paulina002' 'condition' 'R' 'group' 'ICA' }, ...
	{ 'index' 3 'load' 'data_in_groups\ICA\ERSP-Study\sets\004 michal_ICA_after_BadChanRem_5_R.set' 'subject' 'Michal004' 'condition' 'R' 'group' 'ICA' }, ...
	{ 'index' 4 'load' 'data_in_groups\ICA\ERSP-Study\sets\bernadetta_ICA_after_BadChanRem_5_R.set' 'subject' 'Bernadetta' 'condition' 'R' 'group' 'ICA' }, ...
	{ 'index' 5 'load' 'data_in_groups\ICA\ERSP-Study\sets\darekz3_ICA_after_BadChanRem_5_R.set' 'subject' 'DarekZ3' 'condition' 'R' 'group' 'ICA' }, ...
	{ 'index' 6 'load' 'data_in_groups\ICA\ERSP-Study\sets\gosiapw_ICA_after_BadChanRem_5_R.set' 'subject' 'GosiaPW' 'condition' 'R' 'group' 'ICA' }, ...	
        { 'index' 7 'load' 'data_in_groups\ICA\ERSP-Study\sets\kingapl_ICA_after_BadChanRem_5_R.set' 'subject' 'KingaPl' 'condition' 'R' 'group' 'ICA' }, ...	
        { 'index' 8 'load' 'data_in_groups\ICA\ERSP-Study\sets\martyna_ICA_after_BadChanRem_5_R.set' 'subject' 'Martyna' 'condition' 'R' 'group' 'ICA' }, ...	
        { 'index' 9 'load' 'data_in_groups\ICA\ERSP-Study\sets\monika_ICA_after_BadChanRem_5_R.set' 'subject' 'Monika' 'condition' 'R' 'group' 'ICA' }, ...	
        { 'index' 10 'load' 'data_in_groups\ICA\ERSP-Study\sets\natalia_correct_locs_ICA_after_BadChanRem_5_R.set' 'subject' 'Natalia' 'condition' 'R' 'group' 'ICA' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ICA_R.study', 'filepath', 'data_in_groups\ICA\ERSP-Study\');


% ICA
%Rest
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ICA_Rest', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ICA\ERSP-Study\sets\001 malgorzata_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Malgorzata001' 'condition' 'Rest' 'group' 'ICA' }, ...
	{ 'index' 2 'load' 'data_in_groups\ICA\ERSP-Study\sets\002 paulina_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Paulina002' 'condition' 'Rest' 'group' 'ICA' }, ...
	{ 'index' 3 'load' 'data_in_groups\ICA\ERSP-Study\sets\004 michal_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Michal004' 'condition' 'Rest' 'group' 'ICA' }, ...
	{ 'index' 4 'load' 'data_in_groups\ICA\ERSP-Study\sets\bernadetta_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Bernadetta' 'condition' 'Rest' 'group' 'ICA' }, ...
	{ 'index' 5 'load' 'data_in_groups\ICA\ERSP-Study\sets\darekz3_ICA_after_BadChanRem_5_Rest.set' 'subject' 'DarekZ3' 'condition' 'Rest' 'group' 'ICA' }, ...
	{ 'index' 6 'load' 'data_in_groups\ICA\ERSP-Study\sets\gosiapw_ICA_after_BadChanRem_5_Rest.set' 'subject' 'GosiaPW' 'condition' 'Rest' 'group' 'ICA' }, ...	
        { 'index' 7 'load' 'data_in_groups\ICA\ERSP-Study\sets\kingapl_ICA_after_BadChanRem_5_Rest.set' 'subject' 'KingaPl' 'condition' 'Rest' 'group' 'ICA' }, ...	
        { 'index' 8 'load' 'data_in_groups\ICA\ERSP-Study\sets\martyna_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Martyna' 'condition' 'Rest' 'group' 'ICA' }, ...	
        { 'index' 9 'load' 'data_in_groups\ICA\ERSP-Study\sets\monika_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Monika' 'condition' 'Rest' 'group' 'ICA' }, ...	
        { 'index' 10 'load' 'data_in_groups\ICA\ERSP-Study\sets\natalia_correct_locs_ICA_after_BadChanRem_5_Rest.set' 'subject' 'Natalia' 'condition' 'Rest' 'group' 'ICA' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERSP_Data_ICA_Rest.study', 'filepath', 'data_in_groups\ICA\ERSP-Study\');



