% create study

% ASR
%X
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ASR_X', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ASR\ERP-Study\sets\001 malgorzata_ASR_after_BadChanRem_4_X.set' 'subject' 'Malgorzata001' 'condition' 'X' 'group' 'ASR' }, ...
	{ 'index' 2 'load' 'data_in_groups\ASR\ERP-Study\sets\002 paulina_ASR_after_BadChanRem_4_X.set' 'subject' 'Paulina002' 'condition' 'X' 'group' 'ASR' }, ...
	{ 'index' 3 'load' 'data_in_groups\ASR\ERP-Study\sets\004 michal_ASR_after_BadChanRem_4_X.set' 'subject' 'Michal004' 'condition' 'X' 'group' 'ASR' }, ...
	{ 'index' 4 'load' 'data_in_groups\ASR\ERP-Study\sets\bernadetta_ASR_after_BadChanRem_4_X.set' 'subject' 'Bernadetta' 'condition' 'X' 'group' 'ASR' }, ...
	{ 'index' 5 'load' 'data_in_groups\ASR\ERP-Study\sets\darekz3_ASR_after_BadChanRem_4_X.set' 'subject' 'DarekZ3' 'condition' 'X' 'group' 'ASR' }, ...
	{ 'index' 6 'load' 'data_in_groups\ASR\ERP-Study\sets\gosiapw_ASR_after_BadChanRem_4_X.set' 'subject' 'GosiaPW' 'condition' 'X' 'group' 'ASR' }, ...	
        { 'index' 7 'load' 'data_in_groups\ASR\ERP-Study\sets\kingapl_ASR_after_BadChanRem_4_X.set' 'subject' 'KingaPl' 'condition' 'X' 'group' 'ASR' }, ...	
        { 'index' 8 'load' 'data_in_groups\ASR\ERP-Study\sets\martyna_ASR_after_BadChanRem_4_X.set' 'subject' 'Martyna' 'condition' 'X' 'group' 'ASR' }, ...	
        { 'index' 9 'load' 'data_in_groups\ASR\ERP-Study\sets\monika_ASR_after_BadChanRem_4_X.set' 'subject' 'Monika' 'condition' 'X' 'group' 'ASR' }, ...	
        { 'index' 10 'load' 'data_in_groups\ASR\ERP-Study\sets\natalia_correct_locs_ASR_after_BadChanRem_4_X.set' 'subject' 'Natalia' 'condition' 'X' 'group' 'ASR' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP-Study\');



% ASR
%O
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ASR_O', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ASR\ERP-Study\sets\001 malgorzata_ASR_after_BadChanRem_4_O.set' 'subject' 'Malgorzata001' 'condition' 'O' 'group' 'ASR' }, ...
	{ 'index' 2 'load' 'data_in_groups\ASR\ERP-Study\sets\002 paulina_ASR_after_BadChanRem_4_O.set' 'subject' 'Paulina002' 'condition' 'O' 'group' 'ASR' }, ...
	{ 'index' 3 'load' 'data_in_groups\ASR\ERP-Study\sets\004 michal_ASR_after_BadChanRem_4_O.set' 'subject' 'Michal004' 'condition' 'O' 'group' 'ASR' }, ...
	{ 'index' 4 'load' 'data_in_groups\ASR\ERP-Study\sets\bernadetta_ASR_after_BadChanRem_4_O.set' 'subject' 'Bernadetta' 'condition' 'O' 'group' 'ASR' }, ...
	{ 'index' 5 'load' 'data_in_groups\ASR\ERP-Study\sets\darekz3_ASR_after_BadChanRem_4_O.set' 'subject' 'DarekZ3' 'condition' 'O' 'group' 'ASR' }, ...
	{ 'index' 6 'load' 'data_in_groups\ASR\ERP-Study\sets\gosiapw_ASR_after_BadChanRem_4_O.set' 'subject' 'GosiaPW' 'condition' 'O' 'group' 'ASR' }, ...	
        { 'index' 7 'load' 'data_in_groups\ASR\ERP-Study\sets\kingapl_ASR_after_BadChanRem_4_O.set' 'subject' 'KingaPl' 'condition' 'O' 'group' 'ASR' }, ...	
        { 'index' 8 'load' 'data_in_groups\ASR\ERP-Study\sets\martyna_ASR_after_BadChanRem_4_O.set' 'subject' 'Martyna' 'condition' 'O' 'group' 'ASR' }, ...	
        { 'index' 9 'load' 'data_in_groups\ASR\ERP-Study\sets\monika_ASR_after_BadChanRem_4_O.set' 'subject' 'Monika' 'condition' 'O' 'group' 'ASR' }, ...	
        { 'index' 10 'load' 'data_in_groups\ASR\ERP-Study\sets\natalia_correct_locs_ASR_after_BadChanRem_4_O.set' 'subject' 'Natalia' 'condition' 'O' 'group' 'ASR' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERPDataAfterBaseline_ASR_O.study', 'filepath', 'data_in_groups\ASR\ERP-Study\');




% create study

% ICA
%X
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ICA_X', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ICA\ERP-Study\sets\001 malgorzata_ICA_after_BadChanRem_4_X.set' 'subject' 'Malgorzata001' 'condition' 'X' 'group' 'ICA' }, ...
	{ 'index' 2 'load' 'data_in_groups\ICA\ERP-Study\sets\002 paulina_ICA_after_BadChanRem_4_X.set' 'subject' 'Paulina002' 'condition' 'X' 'group' 'ICA' }, ...
	{ 'index' 3 'load' 'data_in_groups\ICA\ERP-Study\sets\004 michal_ICA_after_BadChanRem_4_X.set' 'subject' 'Michal004' 'condition' 'X' 'group' 'ICA' }, ...
	{ 'index' 4 'load' 'data_in_groups\ICA\ERP-Study\sets\bernadetta_ICA_after_BadChanRem_4_X.set' 'subject' 'Bernadetta' 'condition' 'X' 'group' 'ICA' }, ...
	{ 'index' 5 'load' 'data_in_groups\ICA\ERP-Study\sets\darekz3_ICA_after_BadChanRem_4_X.set' 'subject' 'DarekZ3' 'condition' 'X' 'group' 'ICA' }, ...
	{ 'index' 6 'load' 'data_in_groups\ICA\ERP-Study\sets\gosiapw_ICA_after_BadChanRem_4_X.set' 'subject' 'GosiaPW' 'condition' 'X' 'group' 'ICA' }, ...	
        { 'index' 7 'load' 'data_in_groups\ICA\ERP-Study\sets\kingapl_ICA_after_BadChanRem_4_X.set' 'subject' 'KingaPl' 'condition' 'X' 'group' 'ICA' }, ...	
        { 'index' 8 'load' 'data_in_groups\ICA\ERP-Study\sets\martyna_ICA_after_BadChanRem_4_X.set' 'subject' 'Martyna' 'condition' 'X' 'group' 'ICA' }, ...	
        { 'index' 9 'load' 'data_in_groups\ICA\ERP-Study\sets\monika_ICA_after_BadChanRem_4_X.set' 'subject' 'Monika' 'condition' 'X' 'group' 'ICA' }, ...	
        { 'index' 10 'load' 'data_in_groups\ICA\ERP-Study\sets\natalia_correct_locs_ICA_after_BadChanRem_4_X.set' 'subject' 'Natalia' 'condition' 'X' 'group' 'ICA' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERPDataAfterBaseline_ICA_X.study', 'filepath', 'data_in_groups\ICA\ERP-Study\');



% ICA
%O
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
%[STUDY ALLEEG] = pop_loadstudy('filename', 'ERPDataAfterBaseline_ASR_X.study', 'filepath', 'data_in_groups\ASR\ERP-Study\');
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','ICA_O', 'savedat', 'on', 'commands', { ...
	{ 'index' 1 'load' 'data_in_groups\ICA\ERP-Study\sets\001 malgorzata_ICA_after_BadChanRem_4_O.set' 'subject' 'Malgorzata001' 'condition' 'O' 'group' 'ICA' }, ...
	{ 'index' 2 'load' 'data_in_groups\ICA\ERP-Study\sets\002 paulina_ICA_after_BadChanRem_4_O.set' 'subject' 'Paulina002' 'condition' 'O' 'group' 'ICA' }, ...
	{ 'index' 3 'load' 'data_in_groups\ICA\ERP-Study\sets\004 michal_ICA_after_BadChanRem_4_O.set' 'subject' 'Michal004' 'condition' 'O' 'group' 'ICA' }, ...
	{ 'index' 4 'load' 'data_in_groups\ICA\ERP-Study\sets\bernadetta_ICA_after_BadChanRem_4_O.set' 'subject' 'Bernadetta' 'condition' 'O' 'group' 'ICA' }, ...
	{ 'index' 5 'load' 'data_in_groups\ICA\ERP-Study\sets\darekz3_ICA_after_BadChanRem_4_O.set' 'subject' 'DarekZ3' 'condition' 'O' 'group' 'ICA' }, ...
	{ 'index' 6 'load' 'data_in_groups\ICA\ERP-Study\sets\gosiapw_ICA_after_BadChanRem_4_O.set' 'subject' 'GosiaPW' 'condition' 'O' 'group' 'ICA' }, ...	
        { 'index' 7 'load' 'data_in_groups\ICA\ERP-Study\sets\kingapl_ICA_after_BadChanRem_4_O.set' 'subject' 'KingaPl' 'condition' 'O' 'group' 'ICA' }, ...	
        { 'index' 8 'load' 'data_in_groups\ICA\ERP-Study\sets\martyna_ICA_after_BadChanRem_4_O.set' 'subject' 'Martyna' 'condition' 'O' 'group' 'ICA' }, ...	
        { 'index' 9 'load' 'data_in_groups\ICA\ERP-Study\sets\monika_ICA_after_BadChanRem_4_O.set' 'subject' 'Monika' 'condition' 'O' 'group' 'ICA' }, ...	
        { 'index' 10 'load' 'data_in_groups\ICA\ERP-Study\sets\natalia_correct_locs_ICA_after_BadChanRem_4_O.set' 'subject' 'Natalia' 'condition' 'O' 'group' 'ICA' }},'updatedat','on','savedat','on','rmclust','on');

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
pop_savestudy(STUDY, ALLEEG, 'filename','ERPDataAfterBaseline_ICA_O.study', 'filepath', 'data_in_groups\ICA\ERP-Study\');